uiopen('C:\Users\Jacques-Ezechiel\Downloads\high altitude.xls.xlsx',1);
Low_Time = Low_Alt(:,3);
Low_Input = Low_Alt(:,1);
Low_Output = Low_Alt(:,2);
Low_offset_I = Low_Input(:,1)-Low_Input(1,1); 
Low_offset_O = Low_Output(:,1)-Low_Output(1,1); 
Low_90percent = (Low_offset_O>0.9*Low_offset_O(710,1));
Low_10percent = (Low_offset_O<0.1*Low_offset_O(710,1));
figure(1),plot(Low_Time,Low_offset_I,'linewidth',1);
hold on;
plot(Low_Time,Low_offset_O,'linewidth',2);
plot(Low_Time(Low_90percent),Low_offset_O(Low_90percent),'k','Linewidth',5);
plot(Low_Time(Low_10percent),Low_offset_O(Low_10percent),'k','linewidth',5);
hold off;
figure(4),plot(Low_Time,Low_Input,'linewidth',1);
hold on;
plot(Low_Time,Low_Output,'linewidth',2);
hold off;
High_Time = High_Alt(:,3);
High_Input = High_Alt(:,1);
High_Output = High_Alt(:,2);
High_offset_I = High_Input(:,1)-High_Input(1,1); 
High_offset_O = High_Output(:,1)-High_Output(1,1); 
High_90percent = (High_offset_O>0.9*High_offset_O(464,1));
High_10percent = (High_offset_O<0.1*High_offset_O(464,1));
figure(2),plot(High_Time,High_offset_I);
hold on;
plot(High_Time,High_offset_O,'Linewidth',2);
plot(High_Time(High_90percent),High_offset_O(High_90percent),'k','Linewidth',5);
plot(High_Time(High_10percent),High_offset_O(High_10percent),'k','linewidth',5);
hold off;
figure(3),plot(High_Time,High_Input,'linewidth',1);
hold on;
plot(High_Time,High_Output,'linewidth',2);
hold off;